### ISSUE TITLE
Post Removal Request - UW Homework Solutions

### ISSUE THREAD

**Issue by jsanders89** [uwquad/CSE142-3#1]
Hello,

My name is Jonathan and I work with the introductory computer science courses at the University of Washington. The posts in this repository contain solution code to our homework assignments.

These posts' solution codes are indexed by Google, enabling current students to easily find them and cheat on their assignments.

Would you please remove the CSE142-3 repository or make it private in order to help us enforce our academic policy?

By removing the repository, you would be removing tools that our students could use in academic misconduct.

Thank you,
Jonathan Sanders
Intro Support, Computer Science & Engineering
University of Washington
jsanders@cs.washington.edu
More info on our course: http://courses.cs.washington.edu/courses/cse142/15su/

**Comment by uwquad** [comment]
Hi Jonathan,

Yes, I will do so. I'm not sure how to remove it, but I'll email you back if I have any issues.

Best,
Shelby

**Comment by jsanders89** [comment]
Hi Shelby,

Thank you for taking the time to remove your assignments!

Have a great week,
Jonathan
